**Breast Cancer Prediction Using Logistic Regression**

In [2]:
# import the libraries
import numpy as np
import sklearn.datasets


In [5]:
#getting the dataset

breast_cancer = sklearn.datasets.load_breast_cancer()
print(breast_cancer)


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [7]:
x = breast_cancer.data
y = breast_cancer.target
print(x)
print(y)
print(x.shape,y.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

Import data to the Data Frame

In [9]:
import pandas as pd
data = pd.DataFrame(breast_cancer.data , columns = breast_cancer.feature_names)
#column is feature names should be kept they are feature names 
data['class'] = breast_cancer.target
#class represents the labels here
data.head()


mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [16]:
#To know statistics of the data we use describe
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [14]:
print(data['class'].value_counts())

#To know how many malignant ang benign cases are there in the dataset

1    357
0    212
Name: class, dtype: int64


In [15]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [17]:
data.groupby('class').mean()
#to know the mean values of malignant and benign

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

**Main way to classify the type of cancer**

***The malignant stage cancer the values of the cells are bigger compared to malignant stage cancer ***

***0 is for  Malignant

1 is for  Benign***




Train and Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [21]:
x_train , x_test ,y_train , y_test = train_test_split(x, y ,test_size = 0.1) 
# In the above we have used 0.1% that is 10% of the data for testing purpose

In [24]:
print( y.mean() , y_train.mean() , y_test.mean)
#to get the mean value similar in all the y datasets we use stratify


0.6274165202108963 0.62890625 <built-in method mean of numpy.ndarray object at 0x7f4c08778a80>


In [26]:
x_train , x_test ,y_train , y_test = train_test_split(x, y ,test_size = 0.1 ,stratify=y)
print( y.mean() , y_train.mean() , y_test.mean)

0.6274165202108963 0.626953125 <built-in method mean of numpy.ndarray object at 0x7f4c08782120>


In [29]:
#If any person what to split the data same as others then we can use random state
#random state is used to reproduce the code
x_train , x_test ,y_train , y_test = train_test_split(x, y ,test_size = 0.1 ,stratify=y , random_state =1)


**test_size=== to specify the percentage of test data needed

> 


stratify === to split the data correctly as of the original data

> 


random_state === specific split of data. each value of random_state splits the data differently** 

In [ ]:
#Here the stratify is not useful for x_train and x_test



**Logistic Regression**

In [33]:
#import logistic regression from sklearn
from sklearn.linear_model import LogisticRegression
classifier =  LogisticRegression()
# Loading the logistic regression model to the variable 'classifier'


In [31]:
#To know the meaning of the code we can use below code  
classifier.fit?
#we need to put '?' mark after the dought


In [35]:
classifier.fit(x_train ,y_train )

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

**To check the accuracy of our model**

In [44]:
from sklearn.metrics import accuracy_score
#accuracy_score?#for knowing abt accuracy score
prediction_on_training_data =classifier.predict(x_train)
accuracy_on_training_data = accuracy_score(y_train , prediction_on_training_data)
print('accuracy on traing data :',accuracy_on_training_data )

accuracy on traing data : 0.951171875


In [45]:
prediction_on_test_data =classifier.predict(x_test)
accuracy_on_test_data = accuracy_score(y_test , prediction_on_test_data)
print('accuracy on test data :',accuracy_on_test_data )

accuracy on test data : 0.9298245614035088


Detecting whether the patient has breat cancer in benign or malignant stage

In [51]:
input_data=(13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259
)
#change the input_data to numpy_array to make prediction
input_data=np.asarray(input_data)
print(input_data)
#reshape the array as we are predicting the output for one instance
input_data_reshaped = input_data.reshape(1,-1)
#Prediction 
print(input_data_reshaped)
prediction = classifier.predict(input_data_reshaped)
print(prediction) # returns a list with element [0] if Malignant or returns a list with element [1] if Benign.
if(prediction[0]==0):
  print('The breat cancer is Malignant')
else:
    print('The breast cancer is Benign')

[1.354e+01 1.436e+01 8.746e+01 5.663e+02 9.779e-02 8.129e-02 6.664e-02
 4.781e-02 1.885e-01 5.766e-02 2.699e-01 7.886e-01 2.058e+00 2.356e+01
 8.462e-03 1.460e-02 2.387e-02 1.315e-02 1.980e-02 2.300e-03 1.511e+01
 1.926e+01 9.970e+01 7.112e+02 1.440e-01 1.773e-01 2.390e-01 1.288e-01
 2.977e-01 7.259e-02]
[[1.354e+01 1.436e+01 8.746e+01 5.663e+02 9.779e-02 8.129e-02 6.664e-02
  4.781e-02 1.885e-01 5.766e-02 2.699e-01 7.886e-01 2.058e+00 2.356e+01
  8.462e-03 1.460e-02 2.387e-02 1.315e-02 1.980e-02 2.300e-03 1.511e+01
  1.926e+01 9.970e+01 7.112e+02 1.440e-01 1.773e-01 2.390e-01 1.288e-01
  2.977e-01 7.259e-02]]
[1]
The breast cancer is Benign
